### ISSUE TITLE
No Distribution suitable for Raspbian

### ISSUE THREAD

**Issue by rvandet** [IAmStoxe/wirehole#30]
pi@PiDNS:~/wirehole/wirehole $ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
OK
pi@PiDNS:~/wirehole/wirehole $ 
pi@PiDNS:~/wirehole/wirehole $ sudo add-apt-repository \
>     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>         $(lsb_release -cs) \
>         stable" &&
>     sudo apt-get update &&
>     sudo apt-get install docker-ce docker-ce-cli containerd.io -yqq
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

**Comment by jhedd** [comment]
if you're running raspbian, you're not going to want arch=amd64
